# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_nac', models.DateField(verbose_name='Fecha Nacimiento')),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('foto', models.TextField(blank=True, db_column='foto')),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=80)),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('almuno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conyApp.alumno')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField()),
                ('hora', models.TimeField()),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
            ],
            options={
                'db_table': 'clase',
            },
        ),
        migrations.CreateModel(
            name='ClaseIns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'clase-ins',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('duracion', models.IntegerField(null=True)),
                ('clases', models.IntegerField(null=True)),
                ('estado', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanIns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('almuno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conyApp.alumno')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conyApp.Plan')),
            ],
            options={
                'db_table': 'plan-ins',
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha_nac', models.DateField(verbose_name='Fecha Nacimiento')),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('foto', models.TextField(blank=True, db_column='foto')),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=80)),
            ],
            options={
                'db_table': 'profesor',
            },
        ),
        migrations.AddField(
            model_name='claseins',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conyApp.Profesor'),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='conyApp.Profesor'),
        ),
    ]
